import type { FinanceState } from "@/features/finance/types"

export function getCurrentDateKey(date = new Date()) {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`
}

export function getCurrentMonthKey(date = new Date()) {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`
}

function addMonths(date: Date, amount: number) {
  const next = new Date(date)
  next.setMonth(next.getMonth() + amount)
  return next
}

function makeMonthKeyFromOffset(offset: number) {
  return getCurrentMonthKey(addMonths(new Date(), offset))
}

export function createInitialFinanceState(): FinanceState {
  const now = new Date().toISOString()
  const currentMonth = getCurrentMonthKey()
  const currentDate = getCurrentDateKey()
  const currentDateMinus1 = getCurrentDateKey(addMonths(new Date(), -1))
  const currentDateMinus2 = getCurrentDateKey(addMonths(new Date(), -2))
  const currentDateMinus3 = getCurrentDateKey(addMonths(new Date(), -3))
  const currentDatePlus2 = getCurrentDateKey(addMonths(new Date(), 2))
  const currentDatePlus4 = getCurrentDateKey(addMonths(new Date(), 4))

  return {
    expenses: [
      {
        id: "exp-rent",
        name: "Aluguel",
        category: "Contas fixas",
        monthlyAmount: 1850,
        dueDay: 5,
        totalInstallments: 0,
        remainingInstallments: 0,
        status: "Ativa",
        notes: "Contrato residencial principal.",
        createdAt: now,
      },
      {
        id: "exp-health",
        name: "Plano de saúde",
        category: "Contas fixas",
        monthlyAmount: 420,
        dueDay: 12,
        totalInstallments: 0,
        remainingInstallments: 0,
        status: "Ativa",
        notes: "Reajuste previsto para setembro.",
        createdAt: now,
      },
      {
        id: "exp-streaming",
        name: "Streaming e apps",
        category: "Assinaturas",
        monthlyAmount: 126,
        dueDay: 18,
        totalInstallments: 0,
        remainingInstallments: 0,
        status: "Ativa",
        notes: "Revisar assinaturas trimestralmente.",
        createdAt: now,
      },
      {
        id: "exp-notebook",
        name: "Notebook",
        category: "Parcelamentos",
        monthlyAmount: 389,
        dueDay: 22,
        totalInstallments: 12,
        remainingInstallments: 5,
        status: "Ativa",
        notes: "Compra parcelada sem juros.",
        createdAt: now,
      },
      {
        id: "exp-car",
        name: "Financiamento veículo",
        category: "Financiamentos",
        monthlyAmount: 980,
        dueDay: 25,
        totalInstallments: 48,
        remainingInstallments: 31,
        status: "Ativa",
        notes: "Avaliar amortização quando houver excedente.",
        createdAt: now,
      },
    ],
    incomes: [
      {
        id: "inc-salary",
        name: "Salário principal",
        type: "Salário",
        amount: 7200,
        frequency: "Mensal",
        notes: "Recebimento no quinto dia útil.",
        createdAt: now,
      },
      {
        id: "inc-freelance",
        name: "Projeto freelance recorrente",
        type: "Freelance",
        amount: 1350,
        frequency: "Mensal",
        notes: "Contrato de manutenção.",
        createdAt: now,
      },
      {
        id: "inc-extra",
        name: "Renda extra variável",
        type: "Renda extra",
        amount: 320,
        frequency: "Mensal",
        notes: "Venda de itens e cashback.",
        createdAt: now,
      },
    ],
    goals: [
      {
        id: "goal-macbook",
        name: "MacBook Air",
        notes: "Meta para substituir o notebook atual sem comprometer a reserva.",
        status: "Ativa",
        targetAmount: 12000,
        targetDate: currentDatePlus4,
        createdAt: now,
      },
      {
        id: "goal-reserve",
        name: "Reserva de emergência",
        notes: "Meta principal para segurança financeira.",
        status: "Ativa",
        targetAmount: 20000,
        targetDate: null,
        createdAt: now,
      },
      {
        id: "goal-trip",
        name: "Viagem curta",
        notes: "Meta concluída para descanso no fim do ano.",
        status: "Concluída",
        targetAmount: 5000,
        targetDate: currentDatePlus2,
        createdAt: now,
      },
      {
        id: "goal-course",
        name: "Curso de inglês",
        notes: "Meta sem prazo para estudar no próprio ritmo.",
        status: "Pausada",
        targetAmount: 2400,
        targetDate: null,
        createdAt: now,
      },
    ],
    goalContributions: [
      {
        id: "gcontrib-1",
        goalId: "goal-macbook",
        amount: 1500,
        notes: "Primeiro aporte da meta.",
        date: currentDateMinus3,
        createdAt: now,
      },
      {
        id: "gcontrib-2",
        goalId: "goal-macbook",
        amount: 1200,
        notes: "Aporte após o bônus.",
        date: currentDateMinus2,
        createdAt: now,
      },
      {
        id: "gcontrib-3",
        goalId: "goal-macbook",
        amount: 1400,
        notes: "Aporte complementar.",
        date: currentDateMinus1,
        createdAt: now,
      },
      {
        id: "gcontrib-4",
        goalId: "goal-reserve",
        amount: 2500,
        notes: "Aporte recorrente da reserva.",
        date: currentDateMinus3,
        createdAt: now,
      },
      {
        id: "gcontrib-5",
        goalId: "goal-reserve",
        amount: 2400,
        notes: "Aporte mensal fixo.",
        date: currentDateMinus2,
        createdAt: now,
      },
      {
        id: "gcontrib-6",
        goalId: "goal-reserve",
        amount: 2600,
        notes: "Aporte reforçado.",
        date: currentDateMinus1,
        createdAt: now,
      },
      {
        id: "gcontrib-7",
        goalId: "goal-trip",
        amount: 2000,
        notes: "Primeira parcela da viagem.",
        date: currentDateMinus3,
        createdAt: now,
      },
      {
        id: "gcontrib-8",
        goalId: "goal-trip",
        amount: 3000,
        notes: "Concluindo a meta.",
        date: currentDateMinus2,
        createdAt: now,
      },
    ],
    reminders: [
      {
        id: "rem-app",
        name: "Divisão do app de música",
        person: "João",
        type: "Recorrente",
        amount: 24.9,
        frequency: "Mensal",
        nextDueDate: currentDate,
        totalInstallments: 0,
        remainingInstallments: 0,
        status: "Ativo",
        notes: "Cobrar junto com a renovação da assinatura.",
        createdAt: now,
      },
      {
        id: "rem-loan",
        name: "Empréstimo pessoal",
        person: "Carlos",
        type: "Parcelado",
        amount: 600,
        frequency: "Mensal",
        nextDueDate: getCurrentDateKey(addMonths(new Date(), 1)),
        totalInstallments: 2,
        remainingInstallments: 2,
        status: "Ativo",
        notes: "Valor total de R$ 1.200 em duas parcelas.",
        createdAt: now,
      },
      {
        id: "rem-streaming",
        name: "Plano de streaming compartilhado",
        person: "Marina",
        type: "Recorrente",
        amount: 18,
        frequency: "Mensal",
        nextDueDate: getCurrentDateKey(addMonths(new Date(), -1)),
        totalInstallments: 0,
        remainingInstallments: 0,
        status: "Ativo",
        notes: "Cobrança pendente do mês anterior.",
        createdAt: now,
      },
      {
        id: "rem-course",
        name: "Curso dividido",
        person: "Pedro",
        type: "Parcelado",
        amount: 150,
        frequency: "Mensal",
        nextDueDate: getCurrentDateKey(addMonths(new Date(), 2)),
        totalInstallments: 4,
        remainingInstallments: 2,
        status: "Ativo",
        notes: "Restam duas parcelas do valor total de R$ 600.",
        createdAt: now,
      },
      {
        id: "rem-utilities",
        name: "Conta de internet",
        person: "Ana",
        type: "Recorrente",
        amount: 52.5,
        frequency: "Mensal",
        nextDueDate: getCurrentDateKey(addMonths(new Date(), 1)),
        totalInstallments: 0,
        remainingInstallments: 0,
        status: "Pausado",
        notes: "Suspenso enquanto o valor é revisado.",
        createdAt: now,
      },
    ],
    investments: [
      {
        id: "inv-current",
        month: currentMonth,
        plannedAmount: 1450,
        investedAmount: 1320,
        notes: "Aportes em renda fixa e ETF.",
        createdAt: now,
      },
      {
        id: "inv-1",
        month: makeMonthKeyFromOffset(-1),
        plannedAmount: 1300,
        investedAmount: 1480,
        notes: "Aporte extra com bônus.",
        createdAt: now,
      },
      {
        id: "inv-2",
        month: makeMonthKeyFromOffset(-2),
        plannedAmount: 1200,
        investedAmount: 1200,
        notes: "Meta cumprida.",
        createdAt: now,
      },
      {
        id: "inv-3",
        month: makeMonthKeyFromOffset(-3),
        plannedAmount: 1100,
        investedAmount: 900,
        notes: "Redução por despesa médica.",
        createdAt: now,
      },
    ],
    snapshots: [
      {
        id: "snap-5",
        month: makeMonthKeyFromOffset(-5),
        income: 7810,
        expenses: 3920,
        plannedInvestment: 900,
        investedAmount: 850,
      },
      {
        id: "snap-4",
        month: makeMonthKeyFromOffset(-4),
        income: 8120,
        expenses: 4050,
        plannedInvestment: 1000,
        investedAmount: 1100,
      },
      {
        id: "snap-3",
        month: makeMonthKeyFromOffset(-3),
        income: 7990,
        expenses: 4215,
        plannedInvestment: 1100,
        investedAmount: 900,
      },
      {
        id: "snap-2",
        month: makeMonthKeyFromOffset(-2),
        income: 8420,
        expenses: 3980,
        plannedInvestment: 1200,
        investedAmount: 1200,
      },
      {
        id: "snap-1",
        month: makeMonthKeyFromOffset(-1),
        income: 8870,
        expenses: 4105,
        plannedInvestment: 1300,
        investedAmount: 1480,
      },
    ],
    updatedAt: now,
  }
}
